basic_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: prompts/basic_search_system_prompt.txt
cache:
  base_dir: cache
  type: file
chunks:
  group_by_columns:
  - id
  overlap: 100
  size: 1200
  strategy: sentence
cluster_graph:
  max_cluster_size: 10
community_reports:
  graph_prompt: prompts/community_report_graph.txt
  max_input_length: 8000
  max_length: 2000
  model_id: default_chat_model
  text_prompt: prompts/community_report_text.txt
drift_search:
  chat_model_id: default_chat_model
  concurrency: 1
  drift_k_followups: 3
  embedding_model_id: default_embedding_model
  llm_n: 1
  llm_temperature: 0.1
  local_search_llm_max_gen_tokens: 8192
  local_search_n: 1
  local_search_temperature: 0.1
  local_search_top_k_mapped_entities: 5
  local_search_top_k_relationships: 5
  max_tokens: 8192
  n_depth: 1
  primer_expand_query_prompt: prompts/drift_search_primer_expand_query_prompt.txt
  primer_folds: 3
  primer_prompt: prompts/drift_search_primer_prompt.txt
  prompt: prompts/drift_search_system_prompt.txt
  reduce_prompt: prompts/drift_reduce_prompt.txt
embed_graph:
  enabled: false
embed_text:
  model_id: default_embedding_model
  vector_store_id: default_vector_store
extract_claims:
  description: Any claims or facts that could be relevant to information discovery.
  enabled: false
  max_gleanings: 1
  model_id: default_chat_model
  prompt: prompts/extract_claims.txt
extract_graph:
  continue_prompt: prompts/extract_graph_continue_prompt.txt
  entity_types:
  - organization
  - person
  - anatomy
  - injury
  - symptom
  - syndrome
  - treatment
  - herb
  - formula
  - acupoint
  - equipment
  loop_prompt: prompts/extract_graph_loop_prompt.txt
  max_gleanings: 1
  model_id: default_chat_model
  prompt: prompts/extract_graph.txt
extract_graph_nlp:
  text_analyzer:
    extractor_type: regex_english
global_search:
  chat_model_id: default_chat_model
  concurrency: 1
  dynamic_search_concurrent_coroutines: 1
  dynamic_search_llm: gpt-4o
  knowledge_prompt: prompts/global_search_knowledge_system_prompt.txt
  llm_n: 1
  llm_temperature: 0.1
  map_prompt: prompts/global_search_map_system_prompt.txt
  no_data_answer: prompts/global_search_no_data_answer.txt
  reduce_prompt: prompts/global_search_reduce_system_prompt.txt
input:
  base_dir: input
  file_encoding: utf-8
  file_type: text
  type: file
local_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  llm_n: 1
  llm_temperature: 0.1
  prompt: prompts/local_search_system_prompt.txt
  top_k_entities: 10
  top_k_relationships: 10
models:
  default_chat_model:
    api_base: ${GRAPHRAG_API_BASE}
    api_key: ${GRAPHRAG_API_KEY}
    async_mode: threaded
    auth_type: api_key
    concurrent_requests: 5
    encoding_model: cl100k_base
    max_retries: -1
    model: ${CHAT_MODEL}
    model_supports_json: true
    requests_per_minute: ${chat_model_requests_per_minute}
    retry_strategy: native
    temperature: 0.1
    tokens_per_minute: ${chat_model_tokens_per_minute}
    type: openai_chat
  default_embedding_model:
    api_base: ${GRAPHRAG_API_BASE_EMBEDDING}
    api_key: ${GRAPHRAG_API_KEY}
    async_mode: threaded
    auth_type: api_key
    concurrent_requests: 5
    encoding_model: cl100k_base
    max_retries: -1
    model: ${GRAPHRAG_EMBEDDING_MODEL}
    model_supports_json: true
    requests_per_minute: ${embedding_model_requests_per_minute}
    retry_strategy: native
    tokens_per_minute: ${embedding_model_tokens_per_minute}
    type: openai_embedding
output:
  base_dir: output
  type: file
reporting:
  base_dir: logs
  type: file
snapshots:
  embeddings: false
  graphml: true
summarize_descriptions:
  max_length: 500
  model_id: default_chat_model
  prompt: prompts/summarize_descriptions.txt
umap:
  enabled: false
vector_store:
  default_vector_store:
    container_name: default
    db_uri: output/lancedb
    overwrite: true
    type: lancedb
